apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 058264368002.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:latest
        ports:
        - containerPort: 80
