name: Build Docker Image and Push to ECR

on:
  push:
    branches:
      - dev-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 058264368002.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t ecr-repo .

      - name: Tag image
        run: docker tag ecr-repo:latest 058264368002.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:latest

      - name: Push the image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: docker push 058264368002.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:latest
