name: Build Docker Image and Push to ECR

on:
  push:
    branches:
      - dev-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker image
        run: |
          docker build -t ecr-repo .

      - name: Tag image
        run: |
          docker tag ecr-repo:latest 058264368002.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:latest

      - name: Push the image
        run: |
          docker push 058264368002.dkr.ecr.us-east-1.amazonaws.com/ecr-repo:latest
